### ISSUE TITLE
Incorrect Polymorph button position when the terminal size is set to "Auto"

### ISSUE THREAD

**Issue by GearShocky** [kltyton/Polymorphic-Tom#1]
The UI button for switching recipes does not seem to move down when the terminal size is changed. Expanding it results in polymorph button being stuck in the middle of the item grid.
![javaw_9f9OIbkQKp](https://github.com/user-attachments/assets/12a03d85-4db5-4d1c-8fb7-ba01557b56b1)
![javaw_ND0OVKvb4i](https://github.com/user-attachments/assets/f13213cf-ccb0-461b-bd4c-59ab6cc58a32)

**Comment by kltyton** [comment]
This was fixed in version 1.0.3
![0c343cc339e945e5224e00347227bfa8](https://github.com/user-attachments/assets/c405c49f-298c-4092-993d-fe2e8b000f30)

**Comment by kltyton** [comment]
This was fixed in version 1.0.3

**Comment by GearShocky** [comment]
> This was fixed in version 1.0.3

I recently saw that both polymorph compat mods were taken down from curseforge. Did polymorph devs take it down because “it’s a feature that was there at some point” or is it license related?

**Comment by kltyton** [comment]
> > 此问题已在版本 1.0.3 中修复
> 
> 我最近看到两个 polymorph compat mod 都从 curseforge 中删除了。Polymorph 开发人员将其删除是因为“这是某个时候存在的功能”还是与许可证有关？

It's my fault. I originally wanted to delete a wrong file, but I mistakenly deleted the whole project. 
:(
Now the re-uploaded project is still under review. u can download the latest file at https://mediafilez.forgecdn.net/files/5970/139/polymorphic-tom-1.0.3.jar.
:D
