### ISSUE TITLE
Polymorph Toms Storage icon not working on servers

### ISSUE THREAD

**Issue by NebulaAnimations** [kltyton/Polymorphic-Tom#2]
Hello, the mod works wonderfully when running locally, however when used on a server the polymorph icon does not appear. No bug reports or errors from what I can tell just the button is missing.

Version: Minecraft [1.20.1] | Fabric [0.16.9]

Thanks - Neb

**Comment by kltyton** [comment]
It is a client side mod and cannot be used on the server side

**Comment by kltyton** [comment]
Fixed the issue where it was unavailable on the server
